import {Roboto_Flex} from "next/font/google";
import {Vazirmatn} from "next/font/google";

import "@/styles/globals.css";
import {SessionProvider} from "next-auth/react";
import {auth} from "@/auth";
import {Toaster} from "@/components/ui/sonner";

import localFont from 'next/font/local'
import Footer from "@/components/Footer/Footer";
import SmoothScrolling from "@/components/SmoothScrolling";
import {sanityFetch} from "@/sanity/lib/client";
import Header from "@/components/Header/Header";
import StickyCursor from "@/components/stickyCursor/stickyCursor";

const RobotoFlex = Roboto_Flex({
    // weight: '600',
    subsets: ['latin'],
    display: 'swap',
    axes: ["wdth", "GRAD", "slnt", "opsz", "slnt", "XTRA", "YOPQ", "YTAS", "YTDE", "YTLC", "YTUC", "YTDE", "YTFI"],
    variable:
        '--font-robotoFlex'
})

const HWAtlanticUltraLight = localFont({
    src: 'HWAtlanticUltraLight.woff2',
    weight: '200',
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-atlantic'
})

const vazirmatn = Vazirmatn({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-vazirmatn'
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children, params}) {

    const dataHeader = await sanityFetch({
        // query: `*[_id  == "ffc12c19-e0a3-4fe8-a86c-ee2057e7d869"][0]`,
        // query: `*[_type == 'nav'][0].navItems`,
        query: `*[_type == 'nav' && language == "${params.lang}"][0].navItems`,
        tags: ['nav']
    })

    const session = await auth()

    return (
        // session provider permet du'liser le use session pour du rendu use client
        <SessionProvider session={session}>
            <html lang={params.lang}
                  className={`${RobotoFlex.variable} ${vazirmatn.variable} ${HWAtlanticUltraLight.variable}`}>
            <body className="font-vazirmatn">
            <SmoothScrolling>
                <Toaster/>
                <StickyCursor/>
                <Header dataHeader={dataHeader}/>
                {children}
                <div className="border-t-[1px] border-GreyBlue pb-20"></div>
                <Footer language={params.lang}/>
            </SmoothScrolling>
            </body>
            </html>
        </SessionProvider>

    );
}
